
###
GET http://localhost:5000/api/collections
Content-Type: application/json

###
POST http://localhost:5000/api/add-game
Content-Type: application/json

{
    "name": "Assassin's Creed: Valhalla",
    "rating": 4,
    "age": 12,
    "images": [
        "https://res.cloudinary.com/ahumareze/image/upload/v1660341931/AC_KINGDOM_PREORDER_STANDARD_EDITION_EPIC_Key_Art_Wide_3840x2160-3840x2160-485fe17203671386c71bde8110886c7d_l3rr41.jpg",
        "https://res.cloudinary.com/ahumareze/image/upload/v1660341932/Assassins-Creed-Valhalla-Paris-Expansion-Cavalier_wmlqnt.jpg",
        "https://res.cloudinary.com/ahumareze/image/upload/v1660341930/ubisoft-assassins-creed-valhalla_euk4mu.jpg"
    ],
    "description": "Become Eivor, a Viking raider raised to be a fearless warrior, and lead your clan from icy desolation in Norway to a new home amid the lush farmlands of ninth-century England. Find your settlement and conquer this hostile land by any means to earn a place in Valhalla. England in the age of the Vikings is a fractured nation of petty lords and warring kingdoms. Beneath the chaos lies a rich and untamed land waiting for a new conqueror. Will it be you?",
    "prices": [
        {"name": "ps4", "price": 15000},
        {"name": "ps5", "price": 20000}
    ],
    "developers": "Ubisoft Montreal",
    "releaseDate": "10 November, 2020",
    "category": "action",
    "categoryLink": "action"
}

###
POST http://localhost:5000/api/games
Content-Type: application/json

{
    "category": "adventure"
}

###
GET  http://localhost:5000/api/games
Content-Type: application/json

###
POST http://localhost:5000/api/search
Content-Type: application/json

{
    "name": "Froza Horizon 5"
}

###
GET http://localhost:5000/api/home
Content-Type: application/json