
###
GET http://localhost:5000/api/collections
Content-Type: application/json

###
POST http://localhost:5000/api/add-game
Content-Type: application/json

{
    "name": "God Of War 3",
    "rating": 4,
    "age": 12,
    "images": [
        "https://res.cloudinary.com/ahumareze/image/upload/v1660081649/b4_hxvvtn.jpg",
        "https://res.cloudinary.com/ahumareze/image/upload/v1660081710/god-of-war-iii-remastered-screen-20-ps4-us-16jun15_1245x700_fdfrab.jpg",
        "https://res.cloudinary.com/ahumareze/image/upload/v1660081710/4iDVsamGcLvGqyiEizxi8c_kxtxub.jpg"
    ],
    "description": "Embark on a journey across Teyvat to find your lost sibling and seek answers from The Seven — the gods of each element. Explore this wondrous world, join forces with a diverse range of characters, and unravel the countless mysteries that Teyvat holds. Harness the seven elements to unleash elemental reactions. Anemo, Electro, Hydro, Pyro, Cryo, Dendro, and Geo interact in all sorts of ways, and Vision wielders have the power to turn this to their advantage. Will you vaporize Hydro with Pyro, electro-charge it with Electro, or freeze it with Cryo? Your mastery of the elements will give you the upper hand in battle and exploration.",
    "prices": [
        {"name": "ps4", "price": 21000},
        {"name": "ps5", "price": 22500},
        {"name": "xbox", "price": 24000}
    ],
    "developers": "miHoYo .Ltd",
    "releaseDate": "28 September 2020",
    "category": "adventure",
    "categoryLink": "adventure"
}

###
POST http://localhost:5000/api/games
Content-Type: application/json

{
    "category": "adventure"
}

###
POST  http://localhost:5000/api/selected
Content-Type: application/json

{
    "id": ""
}